<?php

namespace Database\Factories;

use App\Models\Consulta;
use Illuminate\Database\Eloquent\Factories\Factory;
use Faker\Factory as FakerFactory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\EmissaoAtestado>
 */
class EmissaoAtestadoFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $faker = FakerFactory::create('pt_BR');
        $descricoes = [
            'O paciente apresenta sintomas de febre alta e dor muscular, recomendando-se repouso e medicação.',
            'Foi constatada uma infecção viral, necessitando de tratamento antiviral e acompanhamento.',
            'O paciente foi diagnosticado com uma pneumonia leve e deve se afastar por 10 dias.',
            'Foi realizado exame de sangue que indicou anemia, necessitando de tratamento com ferro e acompanhamento.',
            'O paciente apresenta quadro de alergia respiratória, sendo necessário evitar alérgenos e uso de anti-histamínicos.',
            'O paciente sofreu um acidente de trânsito e necessita de repouso e fisioterapia por 4 semanas.',
            'Foi constatada uma inflamação no joelho, recomendando-se repouso, gelo e uso de anti-inflamatórios.',
            'A paciente foi diagnosticada com síndrome do túnel do carpo, necessitando de uso de tala e fisioterapia.',
            'O paciente apresenta sintomas de gastrite, necessitando de dieta específica e uso de medicamentos.',
            'Foi constatado quadro de enxaqueca crônica, recomendando-se acompanhamento neurológico e tratamento medicamentoso.',
            'O paciente apresenta quadro de tosse persistente e febre baixa, sendo necessário tratamento com antibióticos.',
            'Foi constatada uma úlcera gástrica, recomendando-se uso de inibidores da bomba de prótons e dieta específica.',
            'O paciente apresenta sinais de estresse severo, recomendando-se acompanhamento psicológico e descanso.',
            'Foi diagnosticada uma sinusite aguda, necessitando de tratamento com descongestionantes e repouso.',
            'O paciente foi diagnosticado com hernia de disco, recomendando-se fisioterapia e uso de analgésicos.',
            'Foi constatada uma infecção urinária, necessitando de tratamento com antibióticos e aumento da ingestão de líquidos.',
            'O paciente apresenta quadro de asma, recomendando-se uso de broncodilatadores e evitamento de gatilhos.',
            'Foi diagnosticada uma tendinite no ombro, necessitando de repouso, gelo e uso de anti-inflamatórios.',
            'O paciente apresenta sintomas de síndrome gripal, recomendando-se repouso e uso de antitérmicos.',
            'Foi constatada uma gastrite aguda, necessitando de dieta leve e medicação para proteção da mucosa gástrica.',
            'O paciente apresenta sintomas de vertigem e náuseas, necessitando de repouso e tratamento com antieméticos.',
            'O paciente foi diagnosticado com fibromialgia, recomendando-se acompanhamento reumatológico e fisioterapia.',
            'Foi constatada uma infecção de pele, necessitando de tratamento com antibióticos tópicos e cuidados com a higiene.',
            'O paciente apresenta sintomas de gripe, recomendando-se repouso, hidratação e uso de medicamentos antigripais.',
            'Foi diagnosticado um quadro de hipertensão arterial, recomendando-se controle da pressão e acompanhamento cardiológico.',
            'O paciente apresenta sinais de desidratação, necessitando de reposição de líquidos e monitoramento contínuo.',
            'Foi constatada uma fratura óssea, necessitando de imobilização e acompanhamento ortopédico.',
            'O paciente apresenta sintomas de síndrome do pânico, recomendando-se acompanhamento psiquiátrico e terapia.',
            'Foi diagnosticada uma lesão muscular, necessitando de repouso, fisioterapia e uso de analgésicos.',
            'O paciente apresenta sintomas de doença celíaca, recomendando-se dieta livre de glúten e acompanhamento nutricional.',
            'Foi constatada uma infecção por fungos, necessitando de tratamento com antifúngicos e cuidados com a higiene.',
            'O paciente apresenta sintomas de dor abdominal crônica, recomendando-se investigação diagnóstica e tratamento sintomático.',
            'Foi diagnosticada uma arritmia cardíaca, necessitando de acompanhamento cardiológico e uso de medicamentos.',
            'O paciente apresenta quadro de febre e mal-estar, recomendando-se repouso e monitoramento dos sintomas.',
            'Foi constatada uma síndrome metabólica, necessitando de mudanças no estilo de vida e acompanhamento endocrinológico.',
            'O paciente apresenta sintomas de cansaço extremo, recomendando-se avaliação clínica e tratamento conforme diagnóstico.',
            'Foi diagnosticada uma úlcera péptica, necessitando de tratamento com medicamentos antiácidos e dieta adequada.',
            'O paciente apresenta sinais de infecção respiratória, recomendando-se tratamento com antibióticos e repouso.',
            'Foi constatada uma hérnia abdominal, necessitando de acompanhamento cirúrgico e cuidados pós-operatórios.',
            'O paciente apresenta quadro de cefaleia intensa, recomendando-se acompanhamento neurológico e uso de analgésicos.',
            'Foi diagnosticada uma parotidite, necessitando de tratamento com anti-inflamatórios e repouso.',
            'O paciente apresenta sintomas de dor nas articulações, recomendando-se acompanhamento reumatológico e fisioterapia.',
            'Foi constatada uma bronquite crônica, necessitando de tratamento com broncodilatadores e acompanhamento pneumológico.',
            'O paciente apresenta sinais de infecção intestinal, recomendando-se tratamento com antibióticos e dieta leve.',
            'Foi diagnosticada uma rinite alérgica, necessitando de uso de anti-histamínicos e controle de alérgenos.',
            'O paciente apresenta sintomas de fadiga crônica, recomendando-se repouso e investigação clínica.',
            'Foi constatada uma lesão no ligamento, necessitando de repouso, fisioterapia e uso de analgésicos.',
            'O paciente apresenta quadro de dor nas costas, recomendando-se fisioterapia e uso de medicamentos anti-inflamatórios.',
            'Foi diagnosticada uma infecção de ouvido, necessitando de tratamento com antibióticos e cuidados com a higiene.',
            'O paciente apresenta sinais de insônia, recomendando-se acompanhamento psicológico e adoção de boas práticas de sono.',
            'Foi constatada uma síndrome do intestino irritável, necessitando de mudanças na dieta e acompanhamento gastroenterológico.',
            'O paciente apresenta sintomas de cistite, recomendando-se tratamento com antibióticos e aumento da ingestão de líquidos.',
            'Foi diagnosticada uma gastrite crônica, necessitando de acompanhamento gastroenterológico e tratamento com medicamentos.',
            'O paciente apresenta quadro de dor no peito, recomendando-se investigação cardiológica e repouso.',
            'Foi constatada uma tendinite no tornozelo, necessitando de repouso, gelo e uso de anti-inflamatórios.',
            'O paciente apresenta sinais de infecção respiratória, recomendando-se tratamento com antivirais e repouso.',
            'Foi diagnosticada uma lombalgia, necessitando de fisioterapia e uso de analgésicos.',
            'O paciente apresenta sintomas de otite externa, recomendando-se tratamento com antibióticos tópicos e cuidados com a higiene.',
            'Foi constatada uma síndrome de burnout, necessitando de acompanhamento psicológico e mudanças no ambiente de trabalho.',
            'O paciente apresenta quadro de dor abdominal aguda, recomendando-se avaliação médica e tratamento conforme diagnóstico.',
            'Foi diagnosticada uma infecção sinusal, necessitando de tratamento com descongestionantes e repouso.',
            'O paciente apresenta sintomas de síndrome da fadiga crônica, recomendando-se repouso e acompanhamento médico.',
            'Foi constatada uma infecção dentária, necessitando de tratamento odontológico e uso de antibióticos.',
            'O paciente apresenta sinais de refluxo gastroesofágico, recomendando-se tratamento com inibidores da bomba de prótons e dieta específica.',
            'Foi diagnosticada uma sinusite crônica, necessitando de acompanhamento e tratamento com descongestionantes e medicamentos.',
            'O paciente apresenta sintomas de herpes simples, recomendando-se tratamento com antivirais e cuidados com a higiene.',
            'Foi constatada uma condição de saúde mental, necessitando de acompanhamento psicológico e mudanças no estilo de vida.',
            'O paciente apresenta sinais de desidratação severa, recomendando-se reposição de líquidos intravenosa e monitoramento.',
            'Foi diagnosticada uma gastrite erosiva, necessitando de tratamento com medicamentos protetores da mucosa e dieta apropriada.',
            'O paciente apresenta sintomas de tosse seca persistente, recomendando-se tratamento com expectorantes e acompanhamento médico.',
            'Foi constatada uma lesão no menisco, necessitando de repouso, fisioterapia e possível intervenção cirúrgica.',
            'O paciente apresenta sinais de síndrome da apneia obstrutiva do sono, recomendando-se avaliação com especialista em sono e uso de CPAP.',
            'Foi diagnosticada uma insuficiência renal aguda, necessitando de acompanhamento nefrológico e tratamento específico.',
            'O paciente apresenta sintomas de dor muscular generalizada, recomendando-se repouso e uso de analgésicos.',
            'Foi constatada uma infecção cutânea, necessitando de tratamento com antibióticos tópicos e cuidados com a higiene.',
            'O paciente apresenta sinais de tensão muscular, recomendando-se fisioterapia e uso de relaxantes musculares.',
            'Foi diagnosticada uma infecção por vírus influenza, necessitando de tratamento com antivirais e repouso.',
            'O paciente apresenta sintomas de estômago irritado, recomendando-se dieta leve e uso de antiácidos.',
            'Foi constatada uma síndrome de hiperatividade, necessitando de acompanhamento psiquiátrico e tratamento com medicação.',
            'O paciente apresenta sinais de infecção do trato respiratório superior, recomendando-se tratamento com descongestionantes e repouso.',
            'Foi diagnosticada uma infecção de garganta, necessitando de tratamento com antibióticos e cuidados com a higiene.',
            'O paciente apresenta sintomas de alergia alimentar, recomendando-se identificação do alérgeno e tratamento com anti-histamínicos.',
            'Foi constatada uma síndrome do cólon irritável, necessitando de dieta específica e acompanhamento gastroenterológico.',
            'O paciente apresenta sinais de otite média, recomendando-se tratamento com antibióticos e cuidados médicos.',
            'Foi diagnosticada uma dor crônica nas articulações, necessitando de acompanhamento reumatológico e uso de analgésicos.',
            'O paciente apresenta sintomas de febre reumática, recomendando-se tratamento com antibióticos e acompanhamento cardiológico.',
            'Foi constatada uma condição de artrite inflamatória, necessitando de fisioterapia e tratamento com anti-inflamatórios.',
            'O paciente apresenta sinais de síndrome de Raynaud, recomendando-se medidas para aquecimento e acompanhamento reumatológico.',
            'Foi diagnosticada uma infecção por parasitas intestinais, necessitando de tratamento com antiparasitários e dieta específica.',
            'O paciente apresenta sintomas de dor no peito ao respirar, recomendando-se investigação pulmonar e repouso.',
            'Foi constatada uma síndrome de Sjögren, necessitando de acompanhamento reumatológico e tratamento sintomático.',
            'O paciente apresenta sinais de esofagite, recomendando-se tratamento com medicamentos e dieta adequada.',
            'Foi diagnosticada uma infecção vaginal, necessitando de tratamento com antifúngicos e cuidados com a higiene.',
            'O paciente apresenta sintomas de dor nas pernas, recomendando-se avaliação vascular e uso de medicamentos.',
            'Foi constatada uma síndrome da hiperuricemia, necessitando de tratamento com medicamentos e mudanças na dieta.',
            'O paciente apresenta sinais de dor ao engolir, recomendando-se avaliação otorrinolaringológica e tratamento conforme diagnóstico.',
            'Foi diagnosticada uma infecção no fígado, necessitando de acompanhamento hepatológico e tratamento específico.',
            'O paciente apresenta sintomas de desregulação hormonal, recomendando-se acompanhamento endocrinológico e tratamento adequado.',
            'Foi constatada uma infecção respiratória aguda, necessitando de tratamento com antibióticos e repouso.',
            'O paciente apresenta sinais de infecção intestinal parasitária, recomendando-se tratamento com antiparasitários e dieta específica.',
            'Foi diagnosticada uma síndrome de Guillain-Barré, necessitando de acompanhamento neurológico e tratamento intensivo.',
            'O paciente apresenta sintomas de dor na nuca, recomendando-se fisioterapia e uso de analgésicos.',
            'Foi constatada uma condição de fibrose pulmonar, necessitando de acompanhamento pulmonológico e tratamento específico.',
            'O paciente apresenta sinais de infecção viral aguda, recomendando-se repouso e tratamento sintomático.',
            'Foi diagnosticada uma inflamação do pâncreas, necessitando de tratamento com medicamentos e dieta apropriada.',
            'O paciente apresenta sintomas de dor nas costas ao respirar, recomendando-se avaliação médica e tratamento adequado.',
            'Foi constatada uma síndrome do estresse pós-traumático, necessitando de acompanhamento psicológico e tratamento específico.',
            'O paciente apresenta sinais de cãibras musculares frequentes, recomendando-se avaliação médica e uso de suplementos.',
            'Foi diagnosticada uma infecção nos seios da face, necessitando de tratamento com descongestionantes e acompanhamento médico.',
            'O paciente apresenta sintomas de fadiga extrema e fraqueza, recomendando-se repouso e avaliação clínica.',
            'Foi constatada uma condição de esclerose múltipla, necessitando de acompanhamento neurológico e tratamento específico.',
            'O paciente apresenta sinais de dor abdominal intensa, recomendando-se investigação diagnóstica e tratamento conforme necessidade.',
            'Foi diagnosticada uma inflamação no fígado, necessitando de acompanhamento hepatológico e tratamento medicamentoso.',
            'O paciente apresenta sintomas de reações alérgicas severas, recomendando-se uso de anti-histamínicos e acompanhamento médico.',
            'Foi constatada uma infecção ocular, necessitando de tratamento com antibióticos e cuidados com a higiene ocular.',
            'O paciente apresenta sinais de doenças autoimunes, recomendando-se acompanhamento especializado e tratamento imunossupressor.',
            'Foi diagnosticada uma condição de dor nas articulações com rigidez matinal, necessitando de acompanhamento reumatológico.',
            'O paciente apresenta sintomas de dor no peito ao respirar, recomendando-se avaliação médica e tratamento conforme diagnóstico.',
            'Foi constatada uma síndrome de Turner, necessitando de acompanhamento endocrinológico e tratamento específico.',
            'O paciente apresenta sinais de lesão no músculo cardíaco, recomendando-se acompanhamento cardiológico e tratamento intensivo.',
            'Foi diagnosticada uma infecção respiratória crônica, necessitando de tratamento com medicamentos e acompanhamento pulmonológico.',
            'O paciente apresenta sintomas de perda de peso inexplicada, recomendando-se avaliação médica e investigação diagnóstica.',
            'Foi constatada uma infecção de pele por bactéria, necessitando de tratamento com antibióticos e cuidados com a higiene.',
            'O paciente apresenta sinais de dor nas costas com radiação para as pernas, recomendando-se avaliação ortopédica e fisioterapia.',
            'Foi diagnosticada uma síndrome do ovário policístico, necessitando de acompanhamento ginecológico e tratamento hormonal.',
            'O paciente apresenta sintomas de fraqueza muscular, recomendando-se investigação neuromuscular e tratamento específico.',
            'Foi constatada uma infecção do trato urinário superior, necessitando de tratamento com antibióticos e acompanhamento.',
            'O paciente apresenta sinais de dor ao engolir e dificuldade respiratória, recomendando-se avaliação otorrinolaringológica.',
            'Foi diagnosticada uma síndrome da imunodeficiência adquirida, necessitando de acompanhamento especializado e tratamento antirretroviral.',
            'O paciente apresenta sintomas de dor intensa no abdômen, recomendando-se investigação clínica e tratamento conforme diagnóstico.',
            'Foi constatada uma infecção viral sistêmica, necessitando de repouso e tratamento sintomático.',
            'O paciente apresenta sinais de transtorno alimentar, recomendando-se acompanhamento psicológico e nutricional.',
            'Foi diagnosticada uma condição de dor torácica com histórico de trauma, necessitando de avaliação médica e tratamento.',
            'O paciente apresenta sintomas de dor no peito com irradiação para o braço, recomendando-se investigação cardiológica.',
            'Foi constatada uma condição de diabetes tipo 2, necessitando de acompanhamento endocrinológico e controle glicêmico.',
            'O paciente apresenta sinais de cãibras noturnas frequentes, recomendando-se uso de suplementos e avaliação médica.',
            'Foi diagnosticada uma síndrome de premenstrual severa, necessitando de acompanhamento ginecológico e tratamento sintomático.',
            'O paciente apresenta sintomas de dor nas pernas com inchaço, recomendando-se avaliação vascular e tratamento.',
            'Foi constatada uma infecção viral com sintomas gastrointestinais, necessitando de repouso e tratamento sintomático.',
            'O paciente apresenta sinais de síndrome de Horner, recomendando-se avaliação neurológica e investigação clínica.',
            'Foi diagnosticada uma condição de dor nos ombros com limitação de movimento, necessitando de fisioterapia e tratamento.',
            'O paciente apresenta sintomas de febre persistente e calafrios, recomendando-se investigação médica e tratamento.',
            'Foi constatada uma infecção no dente, necessitando de tratamento odontológico e uso de antibióticos.',
            'O paciente apresenta sinais de dor nas articulações e rigidez, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi diagnosticada uma condição de síndrome de Cushing, necessitando de acompanhamento endocrinológico e tratamento adequado.',
            'O paciente apresenta sintomas de dor nas costas com histórico de levantamento de peso, recomendando-se fisioterapia e avaliação.',
            'Foi constatada uma infecção respiratória com sintomas de dor torácica, necessitando de tratamento com medicamentos e repouso.',
            'O paciente apresenta sinais de fibrose cística, recomendando-se acompanhamento pneumológico e tratamento específico.',
            'Foi diagnosticada uma síndrome da fadiga crônica com impacto na qualidade de vida, necessitando de tratamento multidisciplinar.',
            'O paciente apresenta sintomas de dor abdominal com histórico de infecção, recomendando-se avaliação médica e tratamento.',
            'Foi constatada uma condição de síndrome da ativação macrofágica, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de transtorno de ansiedade generalizada, recomendando-se acompanhamento psicológico e tratamento.',
            'Foi diagnosticada uma infecção por Mycobacterium tuberculosis, necessitando de tratamento com antibióticos e acompanhamento.',
            'O paciente apresenta sintomas de dor nos ossos com histórico de osteoporose, recomendando-se acompanhamento ortopédico e tratamento.',
            'Foi constatada uma síndrome de Reye, necessitando de tratamento intensivo e acompanhamento pediátrico.',
            'O paciente apresenta sinais de artrite reumatoide, recomendando-se acompanhamento reumatológico e tratamento específico.',
            'Foi diagnosticada uma infecção do trato urinário com sintomas de dor ao urinar, necessitando de tratamento com antibióticos.',
            'O paciente apresenta sintomas de dor de cabeça intensa e frequente, recomendando-se acompanhamento neurológico e tratamento.',
            'Foi constatada uma condição de síndrome de Prader-Willi, necessitando de acompanhamento multidisciplinar e tratamento adequado.',
            'O paciente apresenta sinais de dor nas articulações com histórico de lesão, recomendando-se fisioterapia e tratamento médico.',
            'Foi diagnosticada uma infecção viral respiratória com sintomas graves, necessitando de tratamento e monitoramento médico.',
            'O paciente apresenta sintomas de perda de memória e confusão, recomendando-se avaliação neurológica e tratamento conforme diagnóstico.',
            'Foi constatada uma síndrome de Edwards, necessitando de acompanhamento especializado e suporte multidisciplinar.',
            'O paciente apresenta sinais de infecção por estafilococos, recomendando-se tratamento com antibióticos e cuidados com a higiene.',
            'Foi diagnosticada uma condição de dor abdominal com histórico de doença inflamatória intestinal, necessitando de tratamento.',
            'O paciente apresenta sintomas de dor nas costas com histórico de hérnia, recomendando-se acompanhamento ortopédico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves, necessitando de tratamento e acompanhamento médico.',
            'O paciente apresenta sinais de transtorno bipolar, recomendando-se acompanhamento psiquiátrico e tratamento específico.',
            'Foi diagnosticada uma infecção dentária com sintomas de dor intensa, necessitando de tratamento odontológico e uso de antibióticos.',
            'O paciente apresenta sintomas de dor no peito com histórico de doença cardíaca, recomendando-se avaliação cardiológica e tratamento.',
            'Foi constatada uma síndrome de Noonan, necessitando de acompanhamento especializado e tratamento adequado.',
            'O paciente apresenta sinais de síndrome da hiperatividade com déficit de atenção, recomendando-se acompanhamento psicológico e tratamento.',
            'Foi diagnosticada uma infecção viral com sintomas de dor abdominal e febre, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sintomas de infecção urinária com dor ao urinar, recomendando-se tratamento com antibióticos e hidratação.',
            'Foi constatada uma condição de síndrome do intestino permeável, necessitando de acompanhamento nutricional e tratamento.',
            'O paciente apresenta sinais de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi diagnosticada uma infecção respiratória com sintomas de tosse e febre, necessitando de tratamento com medicamentos e repouso.',
            'O paciente apresenta sintomas de dor nas costas com histórico de lesão, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma síndrome de Bartter, necessitando de acompanhamento especializado e tratamento medicamentoso.',
            'O paciente apresenta sinais de infecção cutânea com dor e vermelhidão, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma condição de síndrome de Down, necessitando de acompanhamento multidisciplinar e suporte adequado.',
            'O paciente apresenta sintomas de dor no peito e falta de ar, recomendando-se avaliação cardiológica e tratamento conforme diagnóstico.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma condição de síndrome de Turner com sintomas específicos, necessitando de acompanhamento e tratamento adequado.',
            'O paciente apresenta sintomas de dor nas articulações e rigidez, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma síndrome de Ehlers-Danlos, necessitando de acompanhamento especializado e suporte multidisciplinar.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antibióticos e repouso.',
            'Foi diagnosticada uma infecção intestinal com sintomas de dor e febre, necessitando de tratamento com antibióticos e dieta leve.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Alport, necessitando de acompanhamento nefrológico e tratamento adequado.',
            'O paciente apresenta sinais de infecção do trato urinário com sintomas de dor e queixa, recomendando-se tratamento com antibióticos.',
            'Foi diagnosticada uma condição de síndrome de Klinefelter, necessitando de acompanhamento endocrinológico e tratamento especializado.',
            'O paciente apresenta sintomas de dor nas articulações e inchaço, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma síndrome de Patau, necessitando de acompanhamento especializado e suporte multidisciplinar.',
            'O paciente apresenta sinais de dor abdominal com histórico de síndrome do intestino irritável, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma infecção viral com sintomas graves e febre, necessitando de repouso e tratamento sintomático.',
            'O paciente apresenta sintomas de dor nas costas com histórico de lesão, recomendando-se acompanhamento ortopédico e fisioterapia.',
            'Foi constatada uma condição de síndrome de Smith-Lemli-Opitz, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sintomas de dor no peito e falta de ar, recomendando-se avaliação cardiológica e tratamento adequado.',
            'Foi constatada uma infecção viral com sintomas gastrointestinais e febre, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi diagnosticada uma condição de síndrome de Usher com sintomas específicos, necessitando de acompanhamento especializado.',
            'O paciente apresenta sintomas de dor abdominal e febre, recomendando-se investigação clínica e tratamento conforme diagnóstico.',
            'Foi constatada uma síndrome de Goldenhar com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antibióticos e repouso.',
            'Foi diagnosticada uma síndrome de Noonan com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações e rigidez, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma condição de síndrome de Williams com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de doença inflamatória intestinal, recomendando-se tratamento e acompanhamento.',
            'Foi diagnosticada uma síndrome de Down com sintomas específicos, necessitando de acompanhamento multidisciplinar e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Ehlers-Danlos com sintomas específicos, necessitando de acompanhamento especializado e tratamento.',
            'O paciente apresenta sinais de infecção do trato urinário com dor e febre, recomendando-se tratamento com antibióticos e cuidados.',
            'Foi diagnosticada uma síndrome de X-Fragile com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
            'Foi constatada uma infecção viral com sintomas graves e febre alta, necessitando de tratamento sintomático e repouso.',
            'O paciente apresenta sinais de dor abdominal com histórico de gastrite, recomendando-se acompanhamento gastroenterológico e tratamento.',
            'Foi diagnosticada uma síndrome de Patau com sintomas específicos, necessitando de acompanhamento especializado e suporte.',
            'O paciente apresenta sintomas de dor nas costas e dificuldade de movimento, recomendando-se fisioterapia e acompanhamento médico.',
            'Foi constatada uma condição de síndrome de Marfan com sintomas específicos, necessitando de acompanhamento cardiológico e tratamento.',
            'O paciente apresenta sinais de infecção respiratória com sintomas graves, recomendando-se tratamento com antivirais e monitoramento.',
            'Foi diagnosticada uma síndrome de Turner com sintomas específicos, necessitando de acompanhamento endocrinológico e tratamento.',
            'O paciente apresenta sintomas de dor nas articulações com histórico de artrite, recomendando-se acompanhamento reumatológico e tratamento.',
        ];        
        return [
            'id_consulta' => Consulta::inRandomOrder()->first()->id,
            'descricao' => $faker->randomElement($descricoes)
        ];
    }
}
